---
title: "pow_parcel_data_0616"
author: "RI"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
```

```{r reading in the data}
parcel_data <- read.csv("Parcellation_12_21.csv")
View(parcel_data)
```

```{r}
# For now I'm taking out all rows with an NA
parcel_data <- na.omit(parcel_data)
changedFrom <- c()

# Parsing through the land use change.
for(i in 1:nrow(parcel_data)){
  
  if(parcel_data$MLUSE_ini[i] != parcel_data$MLUSE_fnl[i]){
    changedFrom <- c(changedFrom, paste(parcel_data$MLUSE_ini[i], sep=" -> ", parcel_data$MLUSE_fnl[i]))
  }
}

unique(changedFrom)
changedFrom.df <- as.data.frame(table(changedFrom))
#changedFrom.df$Freq <- round(changedFrom.df$Freq/sum(changedFrom.df$Freq), 4) *100
changedFrom.df$perc <- round(changedFrom.df$Freq / sum(changedFrom.df$Freq), 4)*100

# Creating bar chart to find frequency of land use change.
changedFrom1.plt <- ggplot(changedFrom.df, aes(x = reorder(changedFrom, perc), y = perc, fill = changedFrom)) + 
  geom_col() + 
  theme(legend.position = "none") + 
  coord_flip() + 
  geom_text(aes(label = perc), hjust = 0.5) +
  ggtitle("Land use change frequency (%)") +
  ylab("Frequency (%)") + xlab("Land use change type")
changedFrom1.plt

changedFrom2.plt <- ggplot(changedFrom.df, aes(x = "", y = Freq, fill = changedFrom)) + 
  geom_bar(stat = "identity") + 
  theme(legend.position = "right") + 
  coord_flip() + 
  geom_text(aes(label = Freq), hjust = 0.5) +
  coord_polar("y", start = 0) + #looks bad we need to take the scale away
  theme_void()
changedFrom2.plt

```
We can see that the category `5 -> 2`, shows that


```{r}
parcel_data$changedFrom <- paste(parcel_data$MLUSE_ini, sep = " -> ", parcel_data$MLUSE_fnl)

sumAcres <- c()

for(i in 1:length(unique(changedFrom))) {
  sumAcres <- c(sumAcres, round(sum(parcel_data[parcel_data$changedFrom == unique(changedFrom)[i],"Area_acre"]), 2))
}


sumAcres <- as.data.frame(sumAcres)
sumAcres$name <- unique(changedFrom)

sumAcres.plt <- ggplot(sumAcres, aes(x = reorder(name, sumAcres), y = sumAcres, fill = name)) + 
  geom_col() + 
  theme(legend.position = "none") + 
  coord_flip() + 
  geom_text(aes(label = sumAcres), hjust = 0.5) +
  ggtitle("Acres per land use change") + ylab("Acres") + xlab("Land change type")
sumAcres.plt

```
We can see that residential land use is still getting the most amount of land, whether it be from 100+ acre parcels or 20-99 acre parcels.

```{r}
# Making percents?
sumAcres$percs <- round(sumAcres$sumAcres / sum(sumAcres$sumAcres) * 100, 2)

sumAcresPercs.plt <- ggplot(sumAcres, aes(x = reorder(name, percs), y = percs, fill = name)) + 
  geom_col() + 
  theme(legend.position = "none") + 
  coord_flip() + 
  geom_text(aes(label = percs), hjust = 0.5) +
  ggtitle("Acres per land use change (%)") + ylab("Acres (%)") + xlab("Land change type")

sumAcresPercs.plt
```



```{r}
powTotal <- 166528 # we need to see how this number changed back from 2021, cause this might be the most recent measurement of how big Powhatan is, but in 2021 it might have been smaller.
sumAcres$totalPercent <- sumAcres$sumAcres / powTotal

totalPerc.plt <- ggplot(sumAcres, aes(x = reorder(name, totalPercent), y = totalPercent, fill = name)) + 
  geom_col() + 
  theme(legend.position = "none") + 
  coord_flip() + 
  geom_text(aes(label = totalPercent), hjust = 0.5)

totalPerc.plt
```


```{r}
# Whole dataset graph to look for 

totalLU <- paste(parcel_data$MLUSE_ini, sep=" -> ", parcel_data$MLUSE_fnl)
totalLU.cat <- unique(totalLU)

value.df <- data.frame(ini = parcel_data$MTOTPR_ini, fnl = parcel_data$MTOTPR_fnl, name = totalLU)

value.grouped <- value.df %>% group_by(name) %>% summarize(total_ini = sum(ini), total_fnl = sum(fnl))


# making the data.frame
plot.df <- data.frame(name = c(totalLU, totalLU), value = c(parcel_data$MTOTPR_ini, parcel_data$MTOTPR_fnl), time = c(rep("ini", nrow(parcel_data)), rep("fnl", nrow(parcel_data))))

plot.df <- plot.df %>% group_by(name, time) %>% summarize(total = sum(value))
ggplot(plot.df, aes(x = name, y = total, fill = time)) + geom_col(position = "dodge") + theme(axis.text.x=element_text(angle = 90))
```


```{r}
LU <- c(1, 2, 3, 4, 41, 42, 5, 6)

newParcel_data <- parcel_data[parcel_data$MLUSE_ini %in% LU & parcel_data$MLUSE_fnl %in% LU,]

plot.df2 <- data.frame(name = c(newParcel_data$changedFrom, newParcel_data$changedFrom), value = c(newParcel_data$MTOTPR_ini, newParcel_data$MTOTPR_fnl), time = c(rep("ini", nrow(newParcel_data)), rep("fnl", nrow(newParcel_data))))

plot.df2 <- plot.df2 %>% group_by(name, time) %>% summarize(total = sum(value))

ggplot(plot.df2, aes(x = name, y = total, fill = time)) + geom_col(position = "dodge") + theme(axis.text.x=element_text(angle = 90)) 

```

```{r}
value_per_acre.df <- parcel_data %>% group_by(MLUSE_fnl) %>% summarise(totalAcres = sum(Area_acre), totalValue = sum(MTOTPR_fnl))
value_per_acre.df <- value_per_acre.df %>% mutate(valuePerAcre = totalValue/totalAcres)

ggplot(value_per_acre.df[1:4,], aes(x=as.character(MLUSE_fnl), y = valuePerAcre, fill = 1:4)) + geom_col() + theme(legend.position="none")


```




